version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales
        tests:
          - unique:
              column_name: "orders_id ||'-'|| pdt_id"
        columns:
          - name: date_date
            description: date of the purchase
          - name: orders_id
            description: unique order number identifier
          - name: pdt_id
            description: unique product number identifier
          - name: revenue
            description: revenue generated
          - name: quantity
            description: amount of product sold
      - name: product
        identifier: raw_gz_product
        description: product
        columns:
          - name: products_id
            description: primary key unique product number identifier
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: product cost
      - name: ship
        identifier: raw_gz_ship
        description: ship
        columns:
          - name: orders_id
            description: Primary Key unique order number identifier
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping charged fee
          - name: logcost
            description: log cost
          - name: ship_cost
            description: cost of shipping

models:
  - name: stg_raw__products
  - name: stg_raw__sales
  - name: stg_raw__ship
  - name: int_sales_margin
