version: 2
sources:
  - name: raw
    schema: raw_data_demo
    tables:
      - name: sales
        description: raw_gz_sales
      - name: product
        description: raw_gz_product
      - name: ship
        description: raw_gz_ship
